### ISSUE TITLE
nickname improperly expires when there are multiple tabs opened

### ISSUE THREAD

**Issue by rrr-dw** [swe-cola/code-live#76]
문제점
---
닉네임 API는 현재 '사용자가 탭을 닫을 때' 서버에 '닉네임을 릴리즈하도록 요청'하고 있습니다.
이것과 관련해서 몇가지 문제를 발견했습니다.
1. 다수의 탭을 열면 모든 탭이 쿠키를 공유하므로 닉네임도 공유합니다.
하지만 하나의 탭이 닫히면 닉네임이 만료되어 기존 탭들의 정체성이 이상해집니다.
(다시 요청하면 새 닉네임을 받고, 그 전까진 기존의 닉네임을 사용하지만,그 동안 피어의 목록에 자신이 표시되지 않음)
2. 사용자가 갑작스럽게 종료한 경우(인터넷 끊김, 전원 끊김 등) '닉네임을 릴리즈하도록 요청'하는 것이 불가능합니다.
동일한 쿠키를 들고 동일한 문서로 돌아가서 제대로 종료해주면 해결되지만, 그동안 귀신 피어가 남아있게 됩니다.

재현 방법
---
1.의 문제점의 경우
  1. 2개 이상의 탭으로 동일한 문서에 접속합니다. 피어목록에는 모두 동일하게 1명으로 나타납니다.(쿠키가 같아야합니다)
  2. 탭 하나를 닫습니다.
  3. 남은 탭의 피어 목록에서 자신의 이름이 사라집니다.

2.의 문제점의 경우
  1. 2개의 서로 다른 환경``A``,``B``에서 같은 문서에 접속합니다. 이 때 피어목록에는 2명이 표시됩니다.
  2. ``A``에서 인터넷을 끊습니다.
  3. ``A``에서 codelive를 종료합니다.
  4. 그 후 ``A``가 인터넷을 다시 연결해도, ``B``의 피어 목록에는 계속해서 2명이 표시됩니다.

(가능한) 해결 방법
---
- 접속 수를 카운트하고, 탭을 닫을 때 카운트를 하나씩 감소시킵니다. 카운트가 0이 될 때 닉네임을 릴리즈합니다.
이 것은 문제점1은 해결하지만 문제점2는 해결하지 않습니다.
- 닉네임의 릴리즈 결정을 백엔드 측에서 담당합니다.
예를들어, ``socketio``연결을 형성하고, 같은 쿠키의 연결 수를 카운트하다가, 카운트가 0이 되면 닉네임을 릴리즈합니다.
``socketio``는 클라이언트가 말 없이 종료된 경우, timeout제로 기존의 ``beforeunload``와 비슷한 연결 종료 이벤트를 발생시킵니다. 물론 말하고 종료한 경우에도 발생합니다.
이 것은 두 문제점을 모두 해결합니다.

**Comment by deinm** [comment]
저도 이거 어떻게 해결해야 하나 해서 `해결 방법 1` 같은 방법을 생각해 보았는데, 두번째 문제점이 발생한다면 말씀해주신 방법을 사용하는 것이 좋겠네요. 더 좋은 방법이 또 있을지 스크럼 전까지 좀더 찾아보겠습니다!
